# Generated by Django 3.2.5 on 2021-12-08 06:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email_id', models.CharField(max_length=64, validators=[django.core.validators.EmailValidator])),
                ('mobile_number',
                 models.CharField(help_text='Please use the following format: <em>XXX-XXX-XXXX</em>.', max_length=15)),
                ('role', models.CharField(
                    choices=[('regular', "Regular - Can't delete members"), ('admin', 'Admin - Can delete members')],
                    default='regular', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
