# Generated by Django 3.2.5 on 2021-12-10 23:25

import TeamApplication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamApplication', '0002_alter_teammember_email_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='mobile_number',
            field=models.CharField(help_text='Please use the following format: <em>XXX-XXX-XXXX</em>.', max_length=15, validators=[TeamApplication.models.validate_phone_number]),
        ),
    ]
